name: CrazyClaims
main: "com.badbones69.crazyclaims.paper.CrazyClaims"
version: ${version}
api-version: 1.18
description: ${description}
author: "Ryder Belserion"
website: "https://github.com/Crazy-Crew/Crazy-Claims/"

commands:
  test:
    description: A test command.

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.7.0